version: '3.8'

services:
  web:
    container_name: elastic-relationships-web
    build: .
    image: testingdes.azurecr.io/elastic-relationships-web
    ports:
      - 5000:5000
    environment:
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
    networks:
      - testing

  elasticsearch:
    container_name: elastic-relationships-db
    image: bitnami/elasticsearch:8.12.1
    ports:
      - 9200:9200
    environment:
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - discovery.type=single-node
    networks:
      - testing

networks:
  testing:
    driver: bridge
