name: Run Python tests

on: [push]

jobs:
  test:
    name: Run tests (setup-python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'
      - name: Install poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Run tests
        run: |
          poetry run pytest tests/__init__.py
