name: Run Python tests

on: [push]

jobs:
  test:
    environment: testing
    name: Run tests (setup-python)
    runs-on: ubuntu-latest
    env:
      ELASTIC_PASSOWRD: ${{ secrets.ELASTIC_PASSWORD }}
      ELASTIC_USER: ${{ secrets.ELASTIC_USER }}
      ELASTIC_HOST: ${{ secrets.ELASTIC_HOST }}
      ELASTIC_CERTS: ${{ secrets.ELASTIC_CERTS }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'
      - name: Install poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Run tests
        run: |
          poetry run pytest tests/
